H/w#10 flask
TatyanaVysotskaya21/common pull request #21
Opened 2019-11-10 14:21 UTC by TatyanaVysotskaya21

2019-11-20 21:03 UTC, yuriimchg requested changes
привіт
нарешті знайшов час переглянути дз, вибач за затримку 
дз виглядає дуже класно :+1: 

є деякі зауваження, які віддаляють його від ідеальності, крім тих, що в коді:
* лінтер дуже свариться на все, що завгодно
* ті помилки, що стосуються Rooms, також часто стосуються інших сутностей
* інше дз, яке невідомо чому попало до цього в пул реквест

2019-11-21 08:11 UTC, TatyanaVysotskaya21 commented on Flask_lesson#3_HW_10/config.py
> +    SECRET_KEY = "test_key"
наследуется от Config, где есть debug=True

2019-11-21 18:38 UTC, TatyanaVysotskaya21 commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +
когда я добавляю в класс, требует чтобы в функции get, post... list_rooms добавили как аргумент

2019-11-22 23:31 UTC, yuriimchg requested changes
привіт
є ще зауваження

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +        get_rooms = {"number": [room for room in list_rooms if parser_room.parse_args().get('number') == room.number],
коли не задані фільтри повертається порожній список кімнат, хоча `list_rooms` не порожній

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/staff/staff_resourse.py
> +                staff.salary = parser_staff.parse_args().get('salary')
метод PUT не працює
![image](https://user-images.githubusercontent.com/33547678/69467418-82417100-0d90-11ea-97d4-3346a8a64dd2.png)

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/staff/staff_resourse.py
> +        for staff in list_staff:
delete також - тут та сама проблема, що й в put

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/staff/staff_resourse.py
> +        for staff in list_staff:
TypeError: delete() got an unexpected keyword argument 'id'

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/staff/main_staff.py
> +api.add_resource(GetStaff, '/staff', '/staff/<string:id>')
помилки в методах PUT і DELETE через це
```suggestion
api.add_resource(GetStaff, '/staff', '/staff/<string:some_id>')
```

2019-11-22 23:31 UTC, yuriimchg commented on Flask_lesson#3_HW_10/tenants/main_tenants.py
> +api.add_resource(GetTenants, '/tenants', '/tenants/<string:id>')
тут аналогічна ситуація до Staff

2019-11-23 09:35 UTC, TatyanaVysotskaya21 commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +        get_rooms = {"number": [room for room in list_rooms if parser_room.parse_args().get('number') == room.number],
Номер кімнати мав би бути унікальним, оскільки це її ідентифікатор - но мы ведь не используем в этом дз базу данных. Комнаты как объекты хранятся в листе. я не понимаю как в этом случае сделать автоінкрементацію

2019-11-23 12:09 UTC, dimigor commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +                                     parser_room.parse_args().get('price')))
you may just unpucjk this values. Take a look at unpacking in python

2019-11-23 12:09 UTC, dimigor commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +                return room, 200
if you do not find satisfied room you should return error message

2019-11-23 12:09 UTC, dimigor commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +                return self.list_rooms, 200
as above

2019-11-24 21:09 UTC, yuriimchg commented
1. я все ще можу додати будь-яку кімнату, навіть з уже існуючим номером чи від'ємною ціною
![image](https://user-images.githubusercontent.com/33547678/69501629-73cd9380-0f0f-11ea-9787-e1583868e083.png)


2. яку б кімнату я не додав, я не зможу отримати її методом GET, мені виводиться лише початковий список кімнат
![image](https://user-images.githubusercontent.com/33547678/69501624-6e704900-0f0f-11ea-93d4-0ab8a83235d0.png)

![image](https://user-images.githubusercontent.com/33547678/69501608-3832c980-0f0f-11ea-8bfb-2b799d2b353f.png)

2019-11-27 08:49 UTC, dimigor requested changes

2019-11-27 08:49 UTC, dimigor commented on Flask_lesson#3_HW_10/rooms/rooms_resourse.py
> +            else:
this else should be at `for..else` I think

2019-11-27 08:49 UTC, dimigor commented on flask_lesson_2/src/product/blueprint_product.py
> +path_img = '/home/k426/GitHub_repos/common/flask_lesson_2/src/static'
do not hardcode paths

2019-11-27 08:49 UTC, dimigor commented on flask_lesson_2/src/product/blueprint_product.py
> +json_file = 'product.json'
make variables as constants

2019-11-27 08:49 UTC, dimigor commented on flask_lesson_2/src/product/blueprint_product.py
> +    if request.method == 'POST':
you do not have to check request method. You already define only `POST` method in `methods`

2019-11-27 08:49 UTC, dimigor commented on flask_lesson_2/src/product/template/add_product.html
> +{% endblock %}
endline

2019-12-01 09:18 UTC, TatyanaVysotskaya21 commented on flask_lesson_2/src/product/blueprint_product.py
> +path_img = '/home/k426/GitHub_repos/common/flask_lesson_2/src/static'
Это с другой домашки, случайно попало сюда

2019-12-01 09:18 UTC, TatyanaVysotskaya21 commented on flask_lesson_2/src/product/blueprint_product.py
> +json_file = 'product.json'
Это с другой домашки, случайно попало сюда

2019-12-01 09:18 UTC, TatyanaVysotskaya21 commented on flask_lesson_2/src/product/blueprint_product.py
> +    if request.method == 'POST':
Это с другой домашки, случайно попало сюда

2019-12-01 09:19 UTC, TatyanaVysotskaya21 commented on flask_lesson_2/src/product/template/add_product.html
> +{% endblock %}
Это с другой домашки, случайно попало сюда

2019-12-02 08:21 UTC, dimigor approved these changes

2019-12-08 09:25 UTC, merged